# Generated by Django 5.2.8 on 2025-11-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_order_name_order_user_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=5),
        ),
        migrations.AddField(
            model_name='productcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
