# Generated by Django 5.2.8 on 2025-11-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productcomment_file_productcomment_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcomment',
            unique_together=set(),
        ),
    ]
